import React, { useMemo, useState } from 'react';
import { ArrowUpRight, CheckCircle2, ExternalLink, Landmark, Search, ShieldCheck } from 'lucide-react';

const schemes = [
 {name:'PM-KISAN', category:'Income support', description:'Direct income support programme for eligible landholding farmer families.', audience:'Eligible farmer families', source:'https://pmkisan.gov.in/'},
 {name:'Pradhan Mantri Fasal Bima Yojana', category:'Crop insurance', description:'Crop insurance support against specified risks and crop losses under the scheme rules.', audience:'Eligible insured farmers', source:'https://pmfby.gov.in/'},
 {name:'Per Drop More Crop', category:'Irrigation', description:'Promotes efficient water use through micro-irrigation such as drip and sprinkler systems.', audience:'Farmers adopting micro-irrigation', source:'https://pmksy.gov.in/'},
 {name:'Sub-Mission on Agricultural Mechanization', category:'Farm machinery', description:'Supports access to agricultural machinery and mechanization initiatives through government programmes.', audience:'Eligible farmers and groups', source:'https://agrimachinery.nic.in/'},
 {name:'Soil Health Card', category:'Soil health', description:'Provides soil nutrient information and recommendations to support balanced nutrient management.', audience:'Farmers with soil test records', source:'https://soilhealth.dac.gov.in/'},
 {name:'Agriculture Infrastructure Fund', category:'Infrastructure', description:'Financing support for eligible agricultural infrastructure projects and post-harvest assets.', audience:'Eligible farmers, groups and enterprises', source:'https://agriinfra.dac.gov.in/'},
 {name:'Paramparagat Krishi Vikas Yojana', category:'Natural / organic farming', description:'Supports cluster-based approaches for sustainable and organic farming practices.', audience:'Eligible farmer groups and clusters', source:'https://pgsindia-ncof.gov.in/'},
 {name:'Krishi Yantra Dhare', category:'Karnataka', description:'Custom hiring centres help farmers access farm machinery without purchasing every implement.', audience:'Farmers in Karnataka', source:'https://raitamitra.karnataka.gov.in/'},
];

export default function SchemesPage(){
 const [query,setQuery]=useState(''); const [category,setCategory]=useState('All');
 const categories=['All',...new Set(schemes.map(s=>s.category))];
 const filtered=useMemo(()=>schemes.filter(s=>(category==='All'||s.category===category)&&`${s.name} ${s.description} ${s.audience}`.toLowerCase().includes(query.toLowerCase())),[category,query]);
 return <div className="pb-20"><section className="bg-agri-800 text-white"><div className="website-section py-16 sm:py-20"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[0.16em] text-agri-100"><Landmark className="h-4 w-4"/> Government support</span><h1 className="mt-6 max-w-4xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Find schemes and support without getting lost.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-agri-100 sm:text-base">A simple frontend directory for central and Karnataka agriculture schemes, with official application destinations kept one click away.</p></div></section>
 <section className="website-section -mt-8 relative z-10"><div className="website-card p-4"><div className="grid gap-3 lg:grid-cols-[1fr_250px]"><label className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search PM-KISAN, insurance, irrigation..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-11 pr-4 text-sm outline-none focus:border-agri-400 focus:bg-white"/></label><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-700 outline-none">{categories.map(c=><option key={c}>{c}</option>)}</select></div></div></section>
 <section className="website-section py-14"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-agri-600">Scheme directory</p><h2 className="mt-2 text-3xl font-black text-slate-950">Explore support</h2></div><span className="text-sm font-bold text-slate-400">{filtered.length} schemes</span></div><div className="mt-8 grid gap-5 md:grid-cols-2">{filtered.map(s=><article key={s.name} className="website-card p-6 transition hover:border-agri-200 hover:shadow-[0_18px_45px_rgba(15,23,42,0.08)]"><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-agri-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-agri-700">{s.category}</span><Landmark className="h-5 w-5 text-slate-300"/></div><h3 className="mt-5 text-xl font-black text-slate-950">{s.name}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{s.description}</p><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-400">Who it is for</p><p className="mt-1 text-sm font-bold text-slate-700">{s.audience}</p></div><a href={s.source} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-agri-600 px-4 py-3 text-sm font-black text-white hover:bg-agri-700">Official information <ExternalLink className="h-4 w-4"/></a></article>)}</div></section>
 <section className="bg-white border-y border-slate-200/70"><div className="website-section py-14"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-slate-950 p-8 text-white"><ShieldCheck className="h-7 w-7 text-agri-400"/><h2 className="mt-5 text-2xl font-black">Verify before applying</h2><p className="mt-3 text-sm leading-7 text-slate-300">Eligibility, documents, deadlines and benefits can depend on the current official guidelines. Use AgriSphere as a discovery layer and confirm the latest details on the official portal.</p></div><div className="rounded-3xl bg-agri-50 p-8"><CheckCircle2 className="h-7 w-7 text-agri-600"/><h2 className="mt-5 text-2xl font-black text-slate-950">Ready for API integration</h2><p className="mt-3 text-sm leading-7 text-slate-600">The directory is intentionally frontend-friendly. Later, Suhas can replace the static scheme list with live API data without redesigning the page.</p><div className="mt-5 flex items-center gap-2 text-sm font-black text-agri-700">Open-ended architecture <ArrowUpRight className="h-4 w-4"/></div></div></div></div></section></div>;
}
