import React, { useMemo, useState } from 'react';
import { Beaker, CheckCircle2, Droplets, FlaskConical, Layers, Search, Sprout } from 'lucide-react';

const nutrients = [
 {name:'Nitrogen (N)', sign:'Pale or yellow older leaves; slow growth', sources:'Compost, well-decomposed manure and nitrogen fertilizers as recommended'},
 {name:'Phosphorus (P)', sign:'Poor root development and slow early growth', sources:'Phosphorus fertilizers or organic sources based on soil test'},
 {name:'Potassium (K)', sign:'Leaf-edge yellowing or scorching', sources:'Potash sources selected according to crop and soil test'},
 {name:'Zinc (Zn)', sign:'Small leaves, shortened internodes or pale bands', sources:'Zinc fertilizers where deficiency is confirmed'},
];

export default function SoilPage(){
 const [ph,setPh]=useState('6.5'); const [organic,setOrganic]=useState(''); const [query,setQuery]=useState('');
 const phStatus=useMemo(()=>{const p=Number(ph); if(p<5.5)return {label:'Strongly acidic',tone:'red',tip:'Consider a soil test and locally recommended liming practice before major nutrient application.'}; if(p<6.5)return {label:'Slightly acidic',tone:'amber',tip:'Many crops can perform well, but crop-specific nutrient recommendations are still important.'}; if(p<=7.5)return {label:'Near neutral',tone:'green',tip:'A generally favourable pH range for many crops. Maintain organic matter and balanced nutrition.'}; return {label:'Alkaline',tone:'amber',tip:'Check nutrient availability and soil-test recommendations, especially for micronutrients.'}},[ph]);
 const filtered=nutrients.filter(n=>`${n.name} ${n.sign}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="pb-20"><section className="bg-agri-800 text-white"><div className="website-section py-16 sm:py-20"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[0.16em] text-agri-100"><Layers className="h-4 w-4"/> Soil health</span><h1 className="mt-6 max-w-4xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Know your soil before you feed your crop.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-agri-100 sm:text-base">Understand pH, organic matter and nutrient deficiencies, then use soil-test results to make better fertilizer decisions.</p></div></section>
 <section className="website-section py-14 sm:py-16"><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="website-card p-7 sm:p-8"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-agri-50 text-agri-700"><FlaskConical className="h-5 w-5"/></div><div><p className="text-xs font-black uppercase tracking-wider text-agri-600">Quick check</p><h2 className="text-xl font-black text-slate-950">Soil pH guide</h2></div></div><label className="mt-7 block text-sm font-bold text-slate-700">Enter your soil pH<input type="number" min="0" max="14" step="0.1" value={ph} onChange={e=>setPh(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-lg font-black outline-none focus:border-agri-400 focus:bg-white"/></label><div className={`mt-5 rounded-2xl p-5 ${phStatus.tone==='green'?'bg-agri-50':phStatus.tone==='red'?'bg-red-50':'bg-amber-50'}`}><p className="text-sm font-black">{phStatus.label}</p><p className="mt-2 text-sm leading-6 text-slate-600">{phStatus.tip}</p></div></div><div className="rounded-3xl bg-slate-950 p-7 text-white sm:p-8"><Sprout className="h-7 w-7 text-agri-400"/><h2 className="mt-5 text-2xl font-black">Organic matter matters</h2><p className="mt-3 text-sm leading-7 text-slate-300">Regularly adding suitable organic matter can support soil structure, water holding and nutrient cycling. Use well-decomposed material and follow crop-specific recommendations.</p><label className="mt-7 block text-sm font-bold text-slate-200">Organic carbon from soil test (%)<input type="number" min="0" step="0.1" value={organic} onChange={e=>setOrganic(e.target.value)} placeholder="e.g. 0.6" className="mt-2 w-full rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-white placeholder:text-slate-500 outline-none focus:ring-4 focus:ring-agri-500/20"/></label></div></div></section>
 <section className="website-section pb-14"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-agri-600">Nutrient guide</p><h2 className="mt-2 text-3xl font-black text-slate-950">Common deficiency signs</h2></div><div className="relative hidden sm:block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nutrient..." className="rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-4 text-sm outline-none"/></div></div><div className="mt-8 grid gap-5 md:grid-cols-2">{filtered.map(n=><div key={n.name} className="website-card p-6"><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-amber-700"><Beaker className="h-5 w-5"/></div><div><h3 className="font-black text-slate-950">{n.name}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{n.sign}</p><div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600"><span className="font-black text-slate-700">Possible sources:</span> {n.sources}</div></div></div></div>)}</div></section>
 <section className="bg-white border-y border-slate-200/70"><div className="website-section py-14"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-agri-50 p-6"><CheckCircle2 className="h-6 w-6 text-agri-600"/><h3 className="mt-4 font-black">Test before correcting</h3><p className="mt-2 text-sm leading-6 text-slate-500">A soil test is more reliable than guessing fertilizer quantities from symptoms alone.</p></div><div className="rounded-2xl bg-sky-50 p-6"><Droplets className="h-6 w-6 text-sky-600"/><h3 className="mt-4 font-black">Watch drainage</h3><p className="mt-2 text-sm leading-6 text-slate-500">Good nutrient management also depends on appropriate irrigation and drainage.</p></div><div className="rounded-2xl bg-amber-50 p-6"><Layers className="h-6 w-6 text-amber-600"/><h3 className="mt-4 font-black">Keep records</h3><p className="mt-2 text-sm leading-6 text-slate-500">Save pH, NPK and organic carbon values so changes in soil health can be tracked over time.</p></div></div></div></section></div>;
}
