import React, { useMemo, useState } from 'react';
import { AlertTriangle, Bug, Leaf, Search, ShieldCheck, X } from 'lucide-react';

const issues = [
 {name:'Leaf Blight', crop:'Rice', type:'Disease', symptoms:'Brown or grey lesions spreading across leaves.', action:'Remove heavily affected material, improve field sanitation and follow local crop-protection guidance.'},
 {name:'Powdery Mildew', crop:'Chilli', type:'Disease', symptoms:'White powder-like growth on leaves and shoots.', action:'Improve air circulation, avoid excessive humidity and use locally recommended treatment when necessary.'},
 {name:'Aphids', crop:'Vegetables', type:'Pest', symptoms:'Small insects clustered on tender shoots with curling leaves.', action:'Inspect new growth regularly and encourage beneficial insects before considering control measures.'},
 {name:'Fall Armyworm', crop:'Maize', type:'Pest', symptoms:'Window-pane feeding and ragged holes on young leaves.', action:'Scout plants early and follow an integrated pest-management approach.'},
 {name:'Fruit Borer', crop:'Tomato', type:'Pest', symptoms:'Small holes in fruits with feeding damage inside.', action:'Remove damaged fruits, use field scouting and follow approved management recommendations.'},
 {name:'Yellow Mosaic', crop:'Chilli / Vegetables', type:'Disease', symptoms:'Yellow-green mosaic pattern and stunted plant growth.', action:'Remove infected plants where appropriate and manage insect vectors through integrated practices.'},
];

export default function DiseasesPage() {
 const [query,setQuery]=useState(''); const [type,setType]=useState('All'); const [selected,setSelected]=useState(null);
 const filtered=useMemo(()=>issues.filter(i=>(type==='All'||i.type===type)&&`${i.name} ${i.crop} ${i.symptoms}`.toLowerCase().includes(query.toLowerCase())),[query,type]);
 return <div className="pb-20"><section className="bg-agri-800 text-white"><div className="website-section py-16 sm:py-20"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[0.16em] text-agri-100"><Bug className="h-4 w-4"/> Crop protection</span><h1 className="mt-6 max-w-4xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Spot problems early. Protect the crop.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-agri-100 sm:text-base">Browse common crop diseases and pests by symptom, crop and issue type. This UI is ready for the image-diagnosis API integration.</p></div></section>
 <section className="website-section -mt-8 relative z-10"><div className="website-card p-4"><div className="grid gap-3 md:grid-cols-[1fr_auto]" ><label className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search disease, pest, crop or symptom..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-11 pr-4 text-sm outline-none focus:border-agri-400 focus:bg-white"/></label><div className="flex rounded-xl bg-slate-100 p-1">{['All','Disease','Pest'].map(t=><button key={t} onClick={()=>setType(t)} className={`rounded-lg px-4 py-2 text-sm font-bold ${type===t?'bg-white text-agri-700 shadow-sm':'text-slate-500'}`}>{t}</button>)}</div></div></div></section>
 <section className="website-section py-14"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-agri-600">Knowledge base</p><h2 className="mt-2 text-3xl font-black text-slate-950">Common issues</h2></div><span className="text-sm font-bold text-slate-400">{filtered.length} results</span></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map(i=><button key={i.name} onClick={()=>setSelected(i)} className="website-card group p-6 text-left transition hover:-translate-y-1 hover:border-agri-200"><div className="flex items-start justify-between"><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-wider ${i.type==='Pest'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{i.type}</span><Bug className="h-5 w-5 text-slate-300 group-hover:text-agri-500"/></div><h3 className="mt-5 text-lg font-black text-slate-950">{i.name}</h3><p className="mt-1 text-xs font-bold text-agri-600">Common in: {i.crop}</p><p className="mt-4 text-sm leading-6 text-slate-500">{i.symptoms}</p><span className="mt-5 inline-block text-sm font-black text-agri-600">View management guide →</span></button>)}</div></section>
 <section className="bg-white border-y border-slate-200/70"><div className="website-section py-14"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-red-50 p-6"><AlertTriangle className="h-6 w-6 text-red-600"/><h3 className="mt-4 font-black">Check symptoms</h3><p className="mt-2 text-sm leading-6 text-slate-500">Look at several plants rather than relying on one damaged leaf.</p></div><div className="rounded-2xl bg-agri-50 p-6"><ShieldCheck className="h-6 w-6 text-agri-600"/><h3 className="mt-4 font-black">Prefer integrated control</h3><p className="mt-2 text-sm leading-6 text-slate-500">Combine field hygiene, scouting and biological or approved chemical controls where appropriate.</p></div><div className="rounded-2xl bg-sky-50 p-6"><Leaf className="h-6 w-6 text-sky-600"/><h3 className="mt-4 font-black">API-ready diagnosis</h3><p className="mt-2 text-sm leading-6 text-slate-500">The interface can later connect to the project’s image-processing service for photo-based diagnosis.</p></div></div></div></section>
 {selected&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/50 p-5" onClick={()=>setSelected(null)}><div className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${selected.type==='Pest'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{selected.type}</span><h2 className="mt-4 text-2xl font-black text-slate-950">{selected.name}</h2><p className="mt-1 text-sm font-bold text-agri-600">{selected.crop}</p></div><button onClick={()=>setSelected(null)}><X className="h-5 w-5"/></button></div><div className="mt-6 rounded-2xl bg-slate-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Symptoms</p><p className="mt-2 text-sm leading-6 text-slate-700">{selected.symptoms}</p></div><div className="mt-4 rounded-2xl bg-agri-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-agri-700">Suggested approach</p><p className="mt-2 text-sm leading-6 text-agri-900">{selected.action}</p></div></div></div>}
 </div>;
}
